automation.notify_sunrise:
  friendly_name: 通知日出

automation.notify_sunset:
  friendly_name: 通知日落

automation.notify_luvis_for_to_school:
  friendly_name: 提醒卢维斯上学校

automation.notify_luvis_for_wake_up:
  friendly_name: 提醒卢维斯起床了

automation.notify_weather_holiday:
  friendly_name: 节假日天气情况提醒

automation.notify_weather_workday:
  friendly_name: 工作日天气情况提醒

automation.auto_open_printer:
  friendly_name: 自动打开打印机

automation.auto_close_printer:
  friendly_name: 空闲自动关闭打印机

automation.welcome_home:
  friendly_name: 欢迎回家

automation.welcome_guest:
  friendly_name: 欢迎客人

automation.restart_router:
  friendly_name: 自动重启光猫

automation.notify_vipkid:
  friendly_name: 通知儿子上英语课

automation.open_purifying_air:
  friendly_name: 自动打开空气净化器

automation.close_purifying_air:
  friendly_name: 自动关闭空气净化器

automation.notify_open_the_door_more_than_5_minutes:
  friendly_name: 超过5分钟门没关通知微信