- platform: command_line
  name: Echo dot play song id
  command: >-
    cat .alexa_play  | jq .play_song.id
  scan_interval: 1

- platform: command_line
  name: Echo dot play song title
  command: >-
    cat .alexa_play  | jq .play_song.title
  scan_interval: 1

- platform: command_line
  name: Echo dot play song name
  command: >-
    cat .alexa_play  | jq .play_song.name
  scan_interval: 1

- platform: command_line
  name: Echo dot play song author
  command: >-
    cat .alexa_play  | jq .play_song.author
  scan_interval: 1

- platform: command_line
  name: Echo dot play song url
  command: >-
    cat .alexa_play  | jq .play_song.url
  scan_interval: 1

- platform: command_line
  name: Echo dot play song list
  command: >-
    cat .alexa_play  | jq -r .play.audio_url | sed 's/^.*cn\///' | sed 's/.json//'
  scan_interval: 1

- platform: command_line
  name: Echo dot play song state
  command: >-
    cat .alexa_play  | jq -r .play_state
  scan_interval: 1

- platform: template
  sensors:
    playlist:
      friendly_name: 播放列表
      value_template: >-
        {%- if is_state('sensor.echo_dot_play_song_state', 'play') -%}
        正在播放 - {% if is_state('sensor.echo_dot_play_song_list', 'ilike') -%}
          我喜欢的音乐
          {%- elif is_state('sensor.echo_dot_play_song_list', 'recommend') -%}
          每日推荐
          {%- elif is_state('sensor.echo_dot_play_song_list', 'personal_fm') -%}
          私人FM
          {%- endif -%}
        {%- elif is_state('sensor.echo_dot_play_song_state', 'stop') -%}
        已停止播放
        {%- endif -%}
      icon_template: mdi:playlist-play

