- platform: command_line
  name: Echo dot play song id
  command: >-
    cat .alexa_play  | jq .play_song.id
  scan_interval: 1

- platform: command_line
  name: Echo dot play song title
  command: >-
    cat .alexa_play  | jq .play_song.title
  scan_interval: 1

- platform: command_line
  name: Echo dot play song name
  command: >-
    cat .alexa_play  | jq .play_song.name
  scan_interval: 1

- platform: command_line
  name: Echo dot play song author
  command: >-
    cat .alexa_play  | jq .play_song.author
  scan_interval: 1

- platform: command_line
  name: Echo dot play song url
  command: >-
    cat .alexa_play  | jq .play_song.url
  scan_interval: 1