- platform: fastdotcom
  minute: 30
  hour:
    - 0
    - 6
    - 12
    - 18

- platform: speedtest
  server_id: 3633
  minute: 30
  hour:
    - 0
    - 6
    - 12
    - 18
  monitored_conditions:
    - download
    - upload