- platform: mqtt
  state_topic: vipkid/class
  name: VIPKID
  value_template: '{{ value_json.left }}'
  json_attributes:
    - time
    - left
    - teacher
    - number
    - topic
    - lesson_id
    - last_updated