- alias: Home Assistant Start
  trigger:
    platform: homeassistant
    event: start
  action:
    - delay: '00:00:10'
    - service: tts.baidu_say
      data:
        entity_id: media_player.speaker_vlc
        message: '家庭助理已启动完成'