- alias: 'Notify VIPKID'
  trigger:
    - platform: numeric_state
      entity_id: sensor.vipkid
      above: 60
      below: 180

  action:
    - service: script.set_vlc_volume
      data:
        value: 0.6

    - service: tts.baidu_say
      data_template:
        entity_id: media_player.speaker_vlc
        message: >-
          {%- for num in range(0,2) -%}
            卢维斯，今天{{- strptime(states.sensor.vipkid.attributes.time, '%Y-%m-%d %X').strftime('%H') -}}点
            {{- strptime(states.sensor.vipkid.attributes.time, '%Y-%m-%d %X').strftime('%M') -}}分，将要开始和
            {{ states.sensor.vipkid.attributes.teacher }} 老师的英文课！
            赶快进教室准备上课吧！
          {% endfor -%}

    - delay: 00:00:05
    - wait_template: >-
        {{ not is_state('media_player.speaker_vlc', 'playing') }}

    # 恢复播放器的音量
    - service: script.set_volume_to_pre