- alias: 'Open Purifying air'
  trigger:
    - platform: numeric_state
      entity_id: sensor.moji_weather_air_quality
      above: 100
      below: 999

    - platform: numeric_state
      entity_id: sensor.waqi_shanghai_normal_college_primary_division_shanghai
      above: 100
      below: 999

    - platform: numeric_state
      entity_id: sensor.living_room_air_quality
      above: 1
      below: 4

    - platform: numeric_state
      entity_id: sensor.living_room_dust
      above: 3
      below: 10

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: fan.living_room
        state: 'off'

      - condition: or
        conditions:
          - condition: numeric_state
            entity_id: sensor.living_room_air_quality
            above: 1
            below: 4

          - condition: numeric_state
            entity_id: sensor.living_room_dust
            above: 3
            below: 10

  action:
    - service: script.set_vlc_volume
      data_template:
        value: 0.6

    # 9点到23点之间播放声音
    - service: media_player.volume_mute
      entity_id: media_player.speaker_vlc
      data_template:
        is_volume_muted: >-
          {%- if now().strftime("%H")|int >= 9 and now().strftime("%H")|int < 23 -%}
          false
          {%- else -%}
          true
          {%- endif -%}

    - service: tts.baidu_say
      data_template:
        entity_id: media_player.speaker_vlc
        message: >-
          空气质量：
          {%- if states('sensor.waqi_shanghai_normal_college_primary_division_shanghai') | float <= 50 -%}
          优
          {%- elif states('sensor.waqi_shanghai_normal_college_primary_division_shanghai') | float <= 100 -%}
          良
          {%- elif states('sensor.waqi_shanghai_normal_college_primary_division_shanghai') | float <= 150 -%}
          轻度污染
          {%- elif states('sensor.waqi_shanghai_normal_college_primary_division_shanghai') | float <= 200 -%}
          中度污染
          {%- elif states('sensor.waqi_shanghai_normal_college_primary_division_shanghai') | float <= 300 -%}
          重度污染
          {%- else -%}
          严重污染
          {% endif -%}
          ，即将为你打开空气净化器，请关闭门窗。

    - delay: 00:00:05
    - wait_template: >-
        {{ not is_state('media_player.speaker_vlc', 'playing') }}

    # 恢复播放器的音量
    - service: script.set_volume_to_pre

    # 打开净化器
    - service: fan.turn_on
      data_template:
        entity_id: fan.living_room
        speed: >-
          {%- if states('sensor.waqi_shanghai_normal_college_primary_division_shanghai') | float <= 50 -%}
          AUTO
          {%- elif states('sensor.waqi_shanghai_normal_college_primary_division_shanghai') | float <= 100 -%}
          AUTO
          {%- elif states('sensor.waqi_shanghai_normal_college_primary_division_shanghai') | float <= 150 -%}
          4
          {%- elif states('sensor.waqi_shanghai_normal_college_primary_division_shanghai') | float <= 200 -%}
          6
          {%- elif states('sensor.waqi_shanghai_normal_college_primary_division_shanghai') | float <= 300 -%}
          8
          {%- else -%}
          10
          {% endif -%}

    - delay: 00:00:01

    # 摇头
    - service: fan.oscillate
      data_template:
        entity_id: fan.living_room
        oscillating: true



- alias: 'Close Purifying air'
  trigger:
    - platform: numeric_state
      entity_id: sensor.moji_weather_air_quality
      above: 0
      below: 100

    - platform: numeric_state
      entity_id: sensor.waqi_shanghai_normal_college_primary_division_shanghai
      above: 0
      below: 100

    - platform: numeric_state
      entity_id: sensor.living_room_air_quality
      above: 0
      below: 1

    - platform: numeric_state
      entity_id: sensor.living_room_dust
      above: 0
      below: 3

  condition:
    - condition: state
      entity_id: fan.living_room
      state: 'on'

  action:
    - service: script.set_vlc_volume
      data:
        value: 0.6

    # 9点到23点之间播放声音
    - service: media_player.volume_mute
      entity_id: media_player.speaker_vlc
      data_template:
        is_volume_muted: >-
          {%- if now().strftime("%H")|int >= 9 and now().strftime("%H")|int < 23 -%}
          false
          {%- else -%}
          true
          {%- endif -%}

    - service: tts.baidu_say
      data_template:
        entity_id: media_player.speaker_vlc
        message: >
          空气质量：
          {%- if states('sensor.waqi_shanghai_normal_college_primary_division_shanghai') | float <= 50 -%}
          优
          {%- elif states('sensor.waqi_shanghai_normal_college_primary_division_shanghai') | float <= 100 -%}
          良
          {%- elif states('sensor.waqi_shanghai_normal_college_primary_division_shanghai') | float <= 150 -%}
          轻度污染
          {%- elif states('sensor.waqi_shanghai_normal_college_primary_division_shanghai') | float <= 200 -%}
          中度污染
          {%- elif states('sensor.waqi_shanghai_normal_college_primary_division_shanghai') | float <= 300 -%}
          重度污染
          {%- else -%}
          严重污染
          {% endif -%}
          ，即将为你关闭空气净化器，请打开门窗。

    - delay: 00:00:05
    - wait_template: >-
        {{ not is_state('media_player.speaker_vlc', 'playing') }}

    # 恢复播放器的音量
    - service: script.set_volume_to_pre

    # 打开净化器
    - service: fan.turn_off
      data_template:
        entity_id: fan.living_room


